controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    api_test_event:
        path: /api/test/event
        controller: App\Controller\TestController::testEvent
        methods: GET
